/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Opt(IDL.Text),
  'experienceLevel' : IDL.Opt(IDL.Text),
  'industry' : IDL.Opt(IDL.Text),
});
export const MatrixWho = IDL.Variant({
  'systemOrg' : IDL.Null,
  'peerTeam' : IDL.Null,
  'leaderManager' : IDL.Null,
});
export const MatrixType = IDL.Variant({
  'perceptionMindset' : IDL.Null,
  'careerGrowth' : IDL.Null,
  'behaviorActionable' : IDL.Null,
});
export const Time = IDL.Int;
export const Scenario = IDL.Record({
  'who' : IDL.Opt(MatrixWho),
  'suggestions' : IDL.Vec(IDL.Text),
  'text' : IDL.Text,
  'challengeType' : IDL.Opt(MatrixType),
  'timestamp' : Time,
});
export const ChatEntry = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Vec(IDL.Text),
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRecentSubmissions' : IDL.Func([], [IDL.Vec(Scenario)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitScenario' : IDL.Func(
      [IDL.Text, IDL.Opt(MatrixWho), IDL.Opt(MatrixType)],
      [IDL.Vec(IDL.Text)],
      [],
    ),
  'submitFreeChat' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
  'getRecentChats' : IDL.Func([], [IDL.Vec(ChatEntry)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Opt(IDL.Text),
    'experienceLevel' : IDL.Opt(IDL.Text),
    'industry' : IDL.Opt(IDL.Text),
  });
  const MatrixWho = IDL.Variant({
    'systemOrg' : IDL.Null,
    'peerTeam' : IDL.Null,
    'leaderManager' : IDL.Null,
  });
  const MatrixType = IDL.Variant({
    'perceptionMindset' : IDL.Null,
    'careerGrowth' : IDL.Null,
    'behaviorActionable' : IDL.Null,
  });
  const Time = IDL.Int;
  const Scenario = IDL.Record({
    'who' : IDL.Opt(MatrixWho),
    'suggestions' : IDL.Vec(IDL.Text),
    'text' : IDL.Text,
    'challengeType' : IDL.Opt(MatrixType),
    'timestamp' : Time,
  });
  const ChatEntry = IDL.Record({
    'question' : IDL.Text,
    'answer' : IDL.Vec(IDL.Text),
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRecentSubmissions' : IDL.Func([], [IDL.Vec(Scenario)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitScenario' : IDL.Func(
        [IDL.Text, IDL.Opt(MatrixWho), IDL.Opt(MatrixType)],
        [IDL.Vec(IDL.Text)],
        [],
      ),
    'submitFreeChat' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
    'getRecentChats' : IDL.Func([], [IDL.Vec(ChatEntry)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
