/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type MatrixType = { 'perceptionMindset' : null } |
  { 'careerGrowth' : null } |
  { 'behaviorActionable' : null };
export type MatrixWho = { 'systemOrg' : null } |
  { 'peerTeam' : null } |
  { 'leaderManager' : null };
export interface Scenario {
  'who' : [] | [MatrixWho],
  'suggestions' : Array<string>,
  'text' : string,
  'challengeType' : [] | [MatrixType],
  'timestamp' : Time,
}
export type Time = bigint;
export interface ChatEntry {
  'question' : string,
  'answer' : Array<string>,
  'timestamp' : Time,
}
export interface UserProfile {
  'name' : string,
  'role' : [] | [string],
  'experienceLevel' : [] | [string],
  'industry' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRecentSubmissions' : ActorMethod<[], Array<Scenario>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitScenario' : ActorMethod<
    [string, [] | [MatrixWho], [] | [MatrixType]],
    Array<string>
  >,
  'submitFreeChat' : ActorMethod<[string], Array<string>>,
  'getRecentChats' : ActorMethod<[], Array<ChatEntry>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
