/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Category = IDL.Variant({
  'communication' : IDL.Null,
  'workload' : IDL.Null,
  'conflict' : IDL.Null,
  'feedback' : IDL.Null,
  'general' : IDL.Null,
  'escalation' : IDL.Null,
});
export const Scenario = IDL.Record({
  'suggestions' : IDL.Vec(IDL.Text),
  'text' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Opt(Category),
});

export const idlService = IDL.Service({
  'getRecentSubmissions' : IDL.Func([], [IDL.Vec(Scenario)], ['query']),
  'submitScenario' : IDL.Func(
      [IDL.Text, IDL.Opt(Category)],
      [IDL.Vec(IDL.Text)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Category = IDL.Variant({
    'communication' : IDL.Null,
    'workload' : IDL.Null,
    'conflict' : IDL.Null,
    'feedback' : IDL.Null,
    'general' : IDL.Null,
    'escalation' : IDL.Null,
  });
  const Scenario = IDL.Record({
    'suggestions' : IDL.Vec(IDL.Text),
    'text' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Opt(Category),
  });
  
  return IDL.Service({
    'getRecentSubmissions' : IDL.Func([], [IDL.Vec(Scenario)], ['query']),
    'submitScenario' : IDL.Func(
        [IDL.Text, IDL.Opt(Category)],
        [IDL.Vec(IDL.Text)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };